services:
    console_output:
        class: Symfony\Component\Console\Output\ConsoleOutput

    base_station:
        class: Podorozhny\Dissertation\BaseStation
        arguments:
            - '%base_station.x%'
            - '%base_station.y%'

    random_location_sensor_node_factory:
        class: Podorozhny\Dissertation\RandomLocationSensorNodeFactory

    network_builder.random:
        class: Podorozhny\Dissertation\RandomNetworkBuilder

    network_builder.genetic_algorithm:
        class: Podorozhny\Dissertation\GeneticAlgorithmNetworkBuilder
        arguments:
            - '@ga_population_manager'
            - '@console_output'
            - '%genetic.generations_limit%'
            - '%genetic.population_size%'
            - '%genetic.fitness_goal%'
            - '%genetic.initial_cluster_heads_ratio_min%'
            - '%genetic.initial_cluster_heads_ratio_max%'

    one_round_charge_reducer:
        class: Podorozhny\Dissertation\OneRoundChargeReducer
        arguments:
            - '%iterations_per_round%'

    ga_population_manager:
        class: Podorozhny\Dissertation\Ga\PopulationManager
        arguments:
            - '@network_fitness_calculator'
            - '%genetic.population_size%'
            - '%genetic.elite_genotype_rate%'
            - '%genetic.crossover_rate%'
            - '%genetic.mutation_rate%'

    network_fitness_calculator:
        class: Podorozhny\Dissertation\NetworkFitnessCalculator
        arguments:
            - '@one_round_charge_reducer'
            - '@base_station'

    network_runner:
        class: Podorozhny\Dissertation\NetworkRunner
        arguments:
            - '@network_builder.genetic_algorithm'
            - '@one_round_charge_reducer'

    network_exporter:
        class: Podorozhny\Dissertation\NetworkExporter
        arguments:
            - '%field_size.x%'
            - '%field_size.y%'
