services:
    console:
        class: Symfony\Component\Console\Output\ConsoleOutput

    base_station:
        class: Podorozhny\Dissertation\BaseStation
        arguments:
            - ~ # x coordinate (have to be overwritten)
            - ~ # y coordinate (have to be overwritten)

    random_location_node_factory:
        class: Podorozhny\Dissertation\RandomLocationNodeFactory

    network_builder.random:
        class: Podorozhny\Dissertation\RandomNetworkBuilder

    network_builder.genetic_algorithm:
        class: Podorozhny\Dissertation\GeneticAlgorithmNetworkBuilder
        arguments:
            - '@ga_population_manager'
            - '@console'

    one_round_charge_reducer:
        class: Podorozhny\Dissertation\OneRoundChargeReducer

    ga_population_manager:
        class: Podorozhny\Dissertation\Ga\PopulationManager
        arguments:
            - '@network_fitness_calculator'

    network_fitness_calculator:
        class: Podorozhny\Dissertation\NetworkFitnessCalculator
        arguments:
            - '@one_round_charge_reducer'
            - '@base_station'

    network_runner:
        class: Podorozhny\Dissertation\NetworkRunner
        arguments:
#            - '@network_builder.random'
            - '@network_builder.genetic_algorithm'
            - '@one_round_charge_reducer'

    network_exporter:
        class: Podorozhny\Dissertation\NetworkExporter
